apiVersion: v1
kind: Pod
metadata:
  name: ae-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west
  containers:
  - name: pod-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - mountPath: "/home/wangdong"
        name: ae-denoiser
      - mountPath: /dev/shm
        name: dshm    
    resources:
      limits:
        memory: 12Gi
        nvidia.com/gpu: 2
      requests:
        memory: 12Gi
        nvidia.com/gpu: 2
  volumes:
    - name: ae-denoiser
      persistentVolumeClaim:
        claimName: ae-denoiser
    - name: dshm
      emptyDir:
        medium: Memory

